
--- 
pool:
  name: "Azure Pipelines"
trigger: 
  - main
steps: 
   - task: "NodeTool@0" 
     inputs:
       versionSource: 'spec'
       versionFilePath: '6.x' 
   - task: Npm@1
     inputs:
       command: 'install'    
       workingDir: /home/ubuntu/myagent/_work/2/s