---
pool: 
  name: Default
trigger:
  - main
steps:
  - script: |
      sudo apt update
  - script: | 
      sudo apt install nodejs -y
    displayName: 'nodejs install' 
  - script: |
      sudo apt install npm -y 
    displayName: 'npm install'
  - script: |
      npm run build
    displayName: 'npm build'