---
pool:
  name: Default
trigger:
  - main
steps:
  - script: |
      sudo apt update
  - script: |
      sudo apt install nodejs
    displayName: 'nodejs install'
  - script: |
      sudo apt install npm
    displayName: 'npm install'
  - script: |
      - cd js-e2e-express-server
      - npm install package.json
      - npm run build
    displayName: 'npm build'